### ISSUE TITLE
Add `EventLoop` trait

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/event_loop#93]
This will be used to allow wrappers such as piston_window to change the event loop settings.

```Rust
pub trait EventLoop {
    fn set_ups(&mut self, frames: u64);
    fn ups(mut self, frames: u64) -> Self {
        self.set_ups(frames);
        self
    }
    fn set_max_fps(&mut self, frames: u64);
    fn max_fps(mut self, frames: u64) {
        self.set_max_fps(frames);
        self
    }
    fn set_swap_buffers(&mut self, enable: bool);
    fn swap_buffers(mut self, enable: bool) {
        self.set_swap_buffers(enable);
        self
    }
    fn set_bench_mode(&mut self, enable: bool);
    fn bench_mode(mut self, enable: bool) {
        self.set_bench_mode(enable);
        self
    }
}
```

**Comment by bvssvni** [comment]
- [ ] Add `EventLoop` trait
- [ ] Implement `EventLoop` for `WindowEvents`
- [ ] Remove old methods on `WindowEvents`
- [ ] Bump to 0.2.0

**Comment by Ryman** [comment]
@bvssvni Regarding the pattern of `set_foo(&mut self, ..)` and `foo(self, ..)`, can you elaborate on the reasoning behind this? Is it solely for different receiver ownership types, or have you found it enabled more flexible builder style chaining?

**Comment by bvssvni** [comment]
@Ryman I wrote up the rationale here https://github.com/PistonDevelopers/piston/issues/882

**Comment by Ryman** [comment]
@bvssvni Thanks!
